apiVersion: v1
kind: Service
metadata:
  name: {{ include "products-chart.fullname" . }}-products-app
  labels:
    {{- include "products-chart.labels" . | nindent 4 }}
spec:
#  type: NodePort
  ports:
#    - name: http
#      port: 4180
#      protocol: TCP
#      targetPort: 4180
    - port: 8000
      targetPort: http-products
#      targetPort: 8080
#      nodePort: 8080
      protocol: TCP
      name: web-products-app
  selector:
    {{- include "products-chart.selectorLabels" . | nindent 4 }}-products-app
